//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tec.ProductCatalog.CreateProduct.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tec.ProductCatalog.CreateProduct.Entities.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 500 caracteres para la descripción..
        /// </summary>
        internal static string DescriptionMaximumLengthErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionMaximumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos 3 caracteres para la descripción. .
        /// </summary>
        internal static string DescriptionMinimumLengthErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionMinimumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 300 caracteres para la url..
        /// </summary>
        internal static string ImageUrlMaximumLengthErrorMessage {
            get {
                return ResourceManager.GetString("ImageUrlMaximumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos 3 caracteres para la url. .
        /// </summary>
        internal static string ImageUrlMinimumLengthErrorMessage {
            get {
                return ResourceManager.GetString("ImageUrlMinimumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 100 caracteres para el nombre..
        /// </summary>
        internal static string NameMaximumLengthErrorMessage {
            get {
                return ResourceManager.GetString("NameMaximumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos 3 caracteres del nombre. .
        /// </summary>
        internal static string NameMinimumLengthErrorMessage {
            get {
                return ResourceManager.GetString("NameMinimumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido.
        /// </summary>
        internal static string NameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del precio ingresado no es válido..
        /// </summary>
        internal static string PriceInvalidErrorMessage {
            get {
                return ResourceManager.GetString("PriceInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio es requerido.
        /// </summary>
        internal static string PriceRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PriceRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar un máximo de 20 caracteres para el estatus..
        /// </summary>
        internal static string StatusMaximumLengthErrorMessage {
            get {
                return ResourceManager.GetString("StatusMaximumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe proporcionar al menos 3 caracteres para el estatus. .
        /// </summary>
        internal static string StatusMinimumLengthErrorMessage {
            get {
                return ResourceManager.GetString("StatusMinimumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El estatus es requerido.
        /// </summary>
        internal static string StatusRequiredErrorMessage {
            get {
                return ResourceManager.GetString("StatusRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El stock es requerido.
        /// </summary>
        internal static string StockRequiredErrorMessage {
            get {
                return ResourceManager.GetString("StockRequiredErrorMessage", resourceCulture);
            }
        }
    }
}
