// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tec.ProductCatalog.EFCore.Repositories.DbContexts;

#nullable disable

namespace Tec.ProductCatalog.EFCore.Repositories.Migrations
{
    [DbContext(typeof(ProductCatalogDbContext))]
    [Migration("20251119193256_AddInitialDB")]
    partial class AddInitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tec.ProductCatalog.EFCore.Repositories.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pago de matrícula para estudiantes.",
                            ImageUrl = "https://example.com/images/matricula.jpg",
                            Name = "Matrícula Semestral",
                            Price = 350.00m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Suscripción anual a biblioteca virtual.",
                            ImageUrl = "https://example.com/images/biblioteca.jpg",
                            Name = "Acceso Biblioteca Digital",
                            Price = 45.00m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emisión de certificado académico oficial.",
                            ImageUrl = "https://example.com/images/certificado.jpg",
                            Name = "Certificado de Estudios",
                            Price = 15.00m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acceso a curso virtual de inglés nivel básico.",
                            ImageUrl = "https://example.com/images/ingles_basico.jpg",
                            Name = "Curso de Inglés Básico",
                            Price = 120.00m,
                            Status = "Active",
                            Stock = 500
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Curso completo de C# para principiantes.",
                            ImageUrl = "https://example.com/images/csharp.jpg",
                            Name = "Curso de Programación C#",
                            Price = 199.99m,
                            Status = "Active",
                            Stock = 300
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uso de laboratorios en línea para prácticas.",
                            ImageUrl = "https://example.com/images/lab_virtual.jpg",
                            Name = "Acceso a Laboratorios Virtuales",
                            Price = 60.00m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Evaluación especial por suficiencia académica.",
                            ImageUrl = "https://example.com/images/examen.jpg",
                            Name = "Examen de Suficiencia",
                            Price = 25.00m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acceso a tutorías personalizadas.",
                            ImageUrl = "https://example.com/images/tutorias.jpg",
                            Name = "Servicio de Tutorías",
                            Price = 75.00m,
                            Status = "Active",
                            Stock = 500
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kit básico de materiales para laboratorio.",
                            ImageUrl = "https://example.com/images/material_lab.jpg",
                            Name = "Material de Laboratorio",
                            Price = 35.00m,
                            Status = "Active",
                            Stock = 800
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Curso virtual de matemáticas avanzadas.",
                            ImageUrl = "https://example.com/images/matematica.jpg",
                            Name = "Curso de Matemática Avanzada",
                            Price = 150.00m,
                            Status = "Active",
                            Stock = 400
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emisión de carnet para estudiantes.",
                            ImageUrl = "https://example.com/images/carnet.jpg",
                            Name = "Carnet Universitario",
                            Price = 10.00m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acceso al estacionamiento del campus.",
                            ImageUrl = "https://example.com/images/parking.jpg",
                            Name = "Estacionamiento Mensual",
                            Price = 25.00m,
                            Status = "Active",
                            Stock = 200
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Paquete de 200 impresiones.",
                            ImageUrl = "https://example.com/images/impresiones.jpg",
                            Name = "Impresiones y Fotocopias",
                            Price = 8.50m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Membresía mensual del gimnasio estudiantil.",
                            ImageUrl = "https://example.com/images/gimnasio.jpg",
                            Name = "Acceso a Gimnasio",
                            Price = 18.00m,
                            Status = "Active",
                            Stock = 150
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Taller presencial de desarrollo de liderazgo.",
                            ImageUrl = "https://example.com/images/liderazgo.jpg",
                            Name = "Taller de Liderazgo",
                            Price = 90.00m,
                            Status = "Active",
                            Stock = 200
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Membresía mensual para sala de cómputo.",
                            ImageUrl = "https://example.com/images/computo.jpg",
                            Name = "Acceso a Sala de Cómputo",
                            Price = 12.00m,
                            Status = "Active",
                            Stock = 500
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Licencia anual de software educativo.",
                            ImageUrl = "https://example.com/images/software.jpg",
                            Name = "Software Educativo",
                            Price = 70.00m,
                            Status = "Active",
                            Stock = 400
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Curso práctico de robótica y electrónica.",
                            ImageUrl = "https://example.com/images/robotica.jpg",
                            Name = "Curso de Robótica",
                            Price = 220.00m,
                            Status = "Active",
                            Stock = 150
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acceso anual al club universitario.",
                            ImageUrl = "https://example.com/images/debate.jpg",
                            Name = "Membresía Club de Debate",
                            Price = 30.00m,
                            Status = "Active",
                            Stock = 350
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Curso presencial de fotografía artística.",
                            ImageUrl = "https://example.com/images/fotografia.jpg",
                            Name = "Curso de Fotografía",
                            Price = 160.00m,
                            Status = "Active",
                            Stock = 100
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Taller de redacción académica.",
                            ImageUrl = "https://example.com/images/redaccion.jpg",
                            Name = "Taller de Redacción",
                            Price = 40.00m,
                            Status = "Active",
                            Stock = 250
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Paquete de materiales escolares.",
                            ImageUrl = "https://example.com/images/material_didactico.jpg",
                            Name = "Material Didáctico",
                            Price = 20.00m,
                            Status = "Active",
                            Stock = 900
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Acceso premium a plataforma virtual.",
                            ImageUrl = "https://example.com/images/plataforma.jpg",
                            Name = "Acceso Plataforma Virtual",
                            Price = 50.00m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Póliza anual de seguro para estudiantes.",
                            ImageUrl = "https://example.com/images/seguro.jpg",
                            Name = "Seguro Estudiantil",
                            Price = 35.00m,
                            Status = "Active",
                            Stock = 9999
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Curso completo de diseño gráfico.",
                            ImageUrl = "https://example.com/images/diseno.jpg",
                            Name = "Curso de Diseño Gráfico",
                            Price = 180.00m,
                            Status = "Active",
                            Stock = 180
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clase grupal de instrumentos musicales.",
                            ImageUrl = "https://example.com/images/musica.jpg",
                            Name = "Taller de Música",
                            Price = 55.00m,
                            Status = "Active",
                            Stock = 120
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Curso introductorio de gastronomía.",
                            ImageUrl = "https://example.com/images/cocina.jpg",
                            Name = "Curso de Cocina",
                            Price = 95.00m,
                            Status = "Active",
                            Stock = 140
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Membresía mensual al laboratorio químico.",
                            ImageUrl = "https://example.com/images/lab_quimica.jpg",
                            Name = "Acceso Laboratorio de Química",
                            Price = 30.00m,
                            Status = "Active",
                            Stock = 200
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Seminario avanzado para emprendedores.",
                            ImageUrl = "https://example.com/images/emprendimiento.jpg",
                            Name = "Taller de Emprendimiento",
                            Price = 110.00m,
                            Status = "Active",
                            Stock = 170
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Curso avanzado de Microsoft Excel.",
                            ImageUrl = "https://example.com/images/excel.jpg",
                            Name = "Curso de Excel Profesional",
                            Price = 75.00m,
                            Status = "Active",
                            Stock = 500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
