<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Tec.ProductCatalog.CreateProduct.IoC\Tec.ProductCatalog.CreateProduct.IoC.csproj" />
	  <ProjectReference Include="..\Tec.ProductCatalog.CreateProduct.Rest.Endpoints\Tec.ProductCatalog.CreateProduct.Rest.Endpoints.csproj" />
	</ItemGroup>

</Project>
